title: Inal's Gotov
description: Inal's personal webpage
tagline: Inal's personal webpage
url: https://inalgotov.com
contact_email: hello@inalgotov.com
author: Inal Gotov
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_posts"
    values:
      layout: "post"
  - scope:
      path: "tldr"
    values:
      layout: "tldr"