assetsPaths = [ "assets", "CNAME" ]
ignoredPaths = [ "scripts", "README.md", "rocket.toml" ]
baseURL = "/Users/sketch204/Developer/sketch204.github.io/dist"

[[defaults]]
path = "posts"
[defaults.values]
layout = "post"
layoutBlockName = "postContent"

[[defaults]]
path = "tldr"
[defaults.values]
layout = "tldr"
layoutBlockName = "tldrContent"
generateTOC = false

[[defaults]]
path = ""
[defaults.values]
layout = "default"
layoutBlockName = "content"
