linkedin = "https://www.linkedin.com/in/inal-gotov/"
github = "https://github.com/sketch204"
twitter = "https://twitter.com/sketch204"
youtube = "https://www.youtube.com/channel/UCZtsakiMM5CNjkQFVi6aRjQ"
contact_email = "hello@inalgotov.com"
